#!/bin/sh

# Make sure everything is development forever
export NODE_ENV=production

set -e

cd "$(dirname "$0")/.."

echo "==> Installing gem dependencies…"
bundle check --path vendor/gems 2>&1 >/dev/null || {
  bundle install --path vendor/gems
}

echo "==> Installing npm dependencies…"
npm install
